site_name: Documentation Missions Deadlock

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
  language: fr

nav:
  - Accueil:
     - index.md
     - Besoin d'aide: help.md
     - Soumission: submit.md
     - Exemples: challenge-types/code.md
     - Mode: mode/index.md
     - Comment ça marche ?: how-does-it-work.md
  - Types de missions:
     - VsCode: challenge-types/vscode.md
     - Multi-langage: challenge-types/metamorph.md
     - Multi-service: challenge-types/multi-service.md
     - Score: challenge-types/score.md
     - SQL: challenge-types/sql.md
  - Répertoires externes:
     - Pour Commencer: external-repositories-guides/external-repositories.md
     - Guide de l'administrateur: external-repositories-guides/admin-guide.md
     - Guide du mainteneur: external-repositories-guides/maintainer-guide.md
  - A propos:
    - Contribuer: contributing.md

markdown_extensions:
  - markdown.extensions.admonition:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true


